In [16]:
import pandas as pd
import numpy as np
import sqlite3
from sqlalchemy import create_engine

In [17]:
# 1. Load Data
df = pd.read_csv('Campaign_Raw - Campaign_Raw.csv.csv')

In [18]:
df.shape

(10028, 26)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10028 entries, 0 to 10027
Data columns (total 26 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Data Source name                             9399 non-null   object
 1   Date                                         9395 non-null   object
 2   Campaign Name                                9392 non-null   object
 3   Campaign Effective Status                    9383 non-null   object
 4   Ad Set Name                                  9387 non-null   object
 5   Ad Name                                      9382 non-null   object
 6   Country Funnel                               9232 non-null   object
 7   Geo Location Segment                         9360 non-null   object
 8   FB Spent Funnel (INR)                        9278 non-null   float64
 9   Amount Spent (INR)                           9358 non-null   float64
 10  Clicks (all)                                 9362 non-null   float64
 11  Impressions                                  9360 non-null   float64
 12  Page Likes                                   9122 non-null   float64
 13  Landing Page Views                           9359 non-null   float64
 14  Link Clicks                                  9356 non-null   float64
 15  Adds to Cart                                 9369 non-null   float64
 16  Checkouts Initiated                          8983 non-null   float64
 17  Adds of Payment Info                         8950 non-null   float64
 18  Purchases                                    9355 non-null   float64
 19  Purchases Conversion Value (INR)             9358 non-null   float64
 20  Website Contacts                             7455 non-null   float64
 21  Messaging Conversations Started              9364 non-null   float64
 22  Adds to Cart Conversion Value (INR)          9366 non-null   float64
 23  Checkouts Initiated Conversion Value (INR)   8402 non-null   float64
 24  Adds of Payment Info Conversion Value (INR)  8936 non-null   float64
 25  Row Count                                    9350 non-null   float64
dtypes: float64(18), object(8)
memory usage: 2.0+ MB

In [20]:
df.describe()

,FB Spent Funnel (INR),Amount Spent (INR),Clicks (all),Impressions,Page Likes,Landing Page Views,Link Clicks,Adds to Cart,Checkouts Initiated,Adds of Payment Info,Purchases,Purchases Conversion Value (INR),Website Contacts,Messaging Conversations Started,Adds to Cart Conversion Value (INR),Checkouts Initiated Conversion Value (INR),Adds of Payment Info Conversion Value (INR),Row Count
count,9278.000000,9358.000000,9.362000e+03,9.360000e+03,9122.000000,9.359000e+03,9356.000000,9369.000000,8983.000000,8950.000000,9355.000000,9.358000e+03,7455.000000,9364.000000,9.366000e+03,8.402000e+03,8.936000e+03,9350.000000
mean,6355.360368,10022.984526,1.778205e+03,1.092893e+05,0.414383,1.692459e+03,1303.923685,24.496318,1.476567,0.301006,0.997221,6.688348e+04,1.486653,5.787804,6.058349e+05,1.864319e+05,5.582583e+04,6.501497
std,39004.957048,59852.497035,6.702752e+04,1.777644e+06,6.288479,4.389078e+04,20862.287250,236.753517,19.153097,7.962555,13.590950,1.042466e+06,22.117744,56.556824,6.341608e+06,3.082780e+06,1.359560e+06,19.715658
min,-312112.320000,-957413.990000,-3.255600e+06,-3.639065e+06,-77.000000,-3.256500e+04,-30780.000000,-594.000000,-390.000000,-168.000000,-164.000000,-2.552301e+07,-64.000000,-567.000000,-6.226054e+07,-1.092500e+07,-3.010700e+07,-66.000000
25%,28.690000,26.532384,1.000000e+00,4.400000e+01,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
50%,304.870000,300.380000,1.900000e+01,4.010000e+02,0.000000,6.000000e+00,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
75%,1122.520000,1121.392500,9.000000e+01,2.153500e+03,0.000000,5.300000e+01,68.000000,1.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
max,957356.160000,964131.980000,4.164600e+06,7.734387e+07,154.000000,3.795090e+06,935388.000000,7326.000000,936.000000,392.000000,492.000000,2.552301e+07,832.000000,1512.000000,1.706904e+08,1.230960e+08,5.236000e+07,132.000000

In [21]:
df.head(3)

,Data Source name,Date,Campaign Name,Campaign Effective Status,Ad Set Name,Ad Name,Country Funnel,Geo Location Segment,FB Spent Funnel (INR),Amount Spent (INR),...,Checkouts Initiated,Adds of Payment Info,Purchases,Purchases Conversion Value (INR),Website Contacts,Messaging Conversations Started,Adds to Cart Conversion Value (INR),Checkouts Initiated Conversion Value (INR),Adds of Payment Info Conversion Value (INR),Row Count
0,Brand A,01/02/2026,NaN,PAUSED,TOF | LAL 3-5% | Sales | Womens,Custom | Video 2 | EOSS | 15th Dec 25 – Copy,India,India,0.0,0.0,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,1.0
1,Brand A,01/03/2026,Growify | 11th June | TOF | ABO | INDIA | LAL ...,paused,TOF | LAL 3-5% | Sales | Womens,Custom | Video 2 | EOSS | 15th Dec 25 – Copy,India,India,0.0,0.0,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,1.0
2,NaN,20/01/2026,Growify | 11th June | TOF | ABO | INDIA | LAL ...,PAUSED,NaN,NaN,INDIA,India,0.0,0.0,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,1.0

In [22]:
#Clean Column Names
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
    .str.replace(r"[()]", "", regex=True)
)

In [23]:
# Handle Text Inconsistencies
text_cols = [
    'data_source_name', 'campaign_name', 'campaign_effective_status',
    'ad_set_name', 'ad_name', 'country_funnel', 'geo_location_segment'
]

for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.lower()

In [24]:
#Handle Missing & Invalid Values
df.replace(['nan', 'unknown', 'none', ''], np.nan, inplace=True)

In [25]:
df.isnull().sum()

data_source_name                              654
date                                          633
campaign_name                                 667
campaign_effective_status                     673
ad_set_name                                   668
ad_name                                       669
country_funnel                                828
geo_location_segment                          692
fb_spent_funnel_inr                           750
amount_spent_inr                              670
clicks_all                                    666
impressions                                   668
page_likes                                    906
landing_page_views                            669
link_clicks                                   672
adds_to_cart                                  659
checkouts_initiated                          1045
adds_of_payment_info                         1078
purchases                                     673
purchases_conversion_value_inr                670
website_contacts                             2573
messaging_conversations_started               664
adds_to_cart_conversion_value_inr             662
checkouts_initiated_conversion_value_inr     1626
adds_of_payment_info_conversion_value_inr    1092
row_count                                     678
dtype: int64

In [34]:
# Logic Check: Drop records with no date (cannot be used for time-series).
df = df.dropna(subset=['date'])
print(f"Records after date validation: {len(df)}")

Records after date validation: 8380

In [37]:
# Drop rows where the Campaign Name is missing (Identity check)
df = df.dropna(subset=['campaign_name'])

In [38]:
#Identify all numeric columns (float64 and int64)
numeric_cols = df.select_dtypes(include=['number']).columns
numeric_cols

Index(['fb_spent_funnel_inr', 'amount_spent_inr', 'clicks_all', 'impressions',
       'page_likes', 'landing_page_views', 'link_clicks', 'adds_to_cart',
       'checkouts_initiated', 'adds_of_payment_info', 'purchases',
       'purchases_conversion_value_inr', 'website_contacts',
       'messaging_conversations_started', 'adds_to_cart_conversion_value_inr',
       'checkouts_initiated_conversion_value_inr',
       'adds_of_payment_info_conversion_value_inr', 'row_count'],
      dtype='object')

In [39]:
#4. Missing Value Imputation
# - Numeric: Fill with 0 (Missing marketing events = 0 occurrences).
df[numeric_cols] = df[numeric_cols].fillna(0)

C:\Users\DELL\AppData\Local\Temp\ipykernel_14472\2081170789.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[numeric_cols] = df[numeric_cols].fillna(0)

In [40]:
# 3. Verify - this should now show 0 for all numeric types
print(df[numeric_cols].isnull().sum())

fb_spent_funnel_inr                          0
amount_spent_inr                             0
clicks_all                                   0
impressions                                  0
page_likes                                   0
landing_page_views                           0
link_clicks                                  0
adds_to_cart                                 0
checkouts_initiated                          0
adds_of_payment_info                         0
purchases                                    0
purchases_conversion_value_inr               0
website_contacts                             0
messaging_conversations_started              0
adds_to_cart_conversion_value_inr            0
checkouts_initiated_conversion_value_inr     0
adds_of_payment_info_conversion_value_inr    0
row_count                                    0
dtype: int64

In [29]:
# Remove Duplicates
before = len(df)

df.drop_duplicates(inplace=True)

after = len(df)

print("Duplicates removed:", before - after)

Duplicates removed: 1074

In [30]:
# Standardize Business Values
df['data_source_name'] = df['data_source_name'].replace({
    'fb': 'facebook',
    'meta': 'facebook',
    'insta': 'instagram'
})

In [41]:
# 6. Metric Recalculation & Anomaly Flagging
# Detection: Negative spend/clicks. Fix: Absolute values.
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col].abs(), errors='coerce')

C:\Users\DELL\AppData\Local\Temp\ipykernel_14472\4252338132.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col].abs(), errors='coerce')

In [44]:
# CTR: Click Through Rate
df['ctr'] = np.where(df['impressions'] > 0, df['link_clicks'] / df['impressions'], 0)

C:\Users\DELL\AppData\Local\Temp\ipykernel_14472\160551228.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ctr'] = np.where(df['impressions'] > 0, df['link_clicks'] / df['impressions'], 0)

In [46]:
# CPM: Cost Per Mille (1000 impressions)
df['cpm'] = np.where(df['impressions'] > 0, (df['amount_spent_inr'] / df['impressions']) * 1000, 0)

In [47]:
# CPC: Cost Per Click
df['cpc'] = np.where(df['link_clicks'] > 0, df['amount_spent_inr'] / df['link_clicks'], 0)

In [48]:
# ROI (ROAS): Return on Ad Spend
df['roas'] = np.where(df['amount_spent_inr'] > 0, df['purchases_conversion_value_inr'] / df['amount_spent_inr'], 0)

In [50]:
# Data Validation Checks
df['data_source_name'].unique()

array(['brand a', nan, 'brand b'], dtype=object)

In [51]:
# Check Negative Values
df[df['amount_spent_inr'] < 0]

Empty DataFrame
Columns: [data_source_name, date, campaign_name, campaign_effective_status, ad_set_name, ad_name, country_funnel, geo_location_segment, fb_spent_funnel_inr, amount_spent_inr, clicks_all, impressions, page_likes, landing_page_views, link_clicks, adds_to_cart, checkouts_initiated, adds_of_payment_info, purchases, purchases_conversion_value_inr, website_contacts, messaging_conversations_started, adds_to_cart_conversion_value_inr, checkouts_initiated_conversion_value_inr, adds_of_payment_info_conversion_value_inr, row_count, ctr, cpm, cpc, roas]
Index: []

[0 rows x 30 columns]

In [53]:
# Check Missing Critical Columns
df[df['campaign_name'].isnull()]

Empty DataFrame
Columns: [data_source_name, date, campaign_name, campaign_effective_status, ad_set_name, ad_name, country_funnel, geo_location_segment, fb_spent_funnel_inr, amount_spent_inr, clicks_all, impressions, page_likes, landing_page_views, link_clicks, adds_to_cart, checkouts_initiated, adds_of_payment_info, purchases, purchases_conversion_value_inr, website_contacts, messaging_conversations_started, adds_to_cart_conversion_value_inr, checkouts_initiated_conversion_value_inr, adds_of_payment_info_conversion_value_inr, row_count, ctr, cpm, cpc, roas]
Index: []

[0 rows x 30 columns]

In [56]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:1234@localhost:5432/campaign")

df.to_sql("staging_ads", engine, schema="campaign_data", if_exists="replace", index=False)

830