In [38]:
import pandas as pd 
import numpy as np
from datetime import datetime

In [39]:
df = pd.read_csv('Raw_Shopify_Sales - Raw_Shopify_Sales.csv.csv')

In [40]:
df.shape

(5680, 38)

In [41]:
df.head(3)

,Data Source name,Date,Currency,Sales Channel,Transaction Timestamp,Order Created At,Order Updated At,Order ID,Order Name,Country Funnel,...,Average Order Value (INR),New Customer Orders,Returning Customer Orders,Average Items Per Order,Discounts (INR),Row Count,SKU,Customer Sale Type,Customer ID,Shipping Country
0,Brand A,01/08/2026,INR,Online Store,2026-01-08T11:39:42Z,2026-01-08T11:39:43Z,2026-01-08T11:39:44Z,-6.318230e+12,NaN,United Arab Emirates,...,NaN,0.0,NaN,NaN,0.0,1.0,NaN,First-time,9.052170e+12,NaN
1,Brand A,NAN,INR,Online Store,2026-01-13T06:25:45Z,2026-01-13T06:25:47Z,2026-01-13T06:25:48Z,6.324090e+12,#1053,United States,...,NaN,0.0,NaN,NaN,0.0,1.0,NaN,NaN,9.965681e+14,United States
2,Brand A,19/01/2026,INR,Online Store,2026-01-19T16:16:58Z,2026-01-19T16:16:59Z,2026-01-19T16:17:00Z,6.333300e+12,#1055,United States,...,NaN,0.0,NaN,NaN,NaN,1.0,NaN,First-time,-9.979288e+14,United States

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5680 entries, 0 to 5679
Data columns (total 38 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Data Source name           5236 non-null   object
 1   Date                       5218 non-null   object
 2   Currency                   5230 non-null   object
 3   Sales Channel              5230 non-null   object
 4   Transaction Timestamp      5225 non-null   object
 5   Order Created At           5245 non-null   object
 6   Order Updated At           5238 non-null   object
 7   Order ID                   5230 non-null   float64
 8   Order Name                 5237 non-null   object
 9   Country Funnel             5231 non-null   object
 10  Geo Location Segment       5237 non-null   object
 11  Billing Country            5202 non-null   object
 12  Billing Province           4942 non-null   object
 13  Billing City               5039 non-null   object
 14  Order Tags                 3761 non-null   object
 15  Product ID                 3142 non-null   float64
 16  Product Title              3200 non-null   object
 17  Product Tags               3233 non-null   object
 18  Product Type               3202 non-null   object
 19  Variant Title              3201 non-null   object
 20  Gross Sales (INR)          5221 non-null   float64
 21  Net Sales (INR)            5223 non-null   float64
 22  Total Sales (INR)          5224 non-null   float64
 23  Orders                     5219 non-null   float64
 24  Returns (INR)              5203 non-null   float64
 25  Return Rate                3211 non-null   float64
 26  Items Sold                 5089 non-null   float64
 27  Items Returned             283 non-null    float64
 28  Average Order Value (INR)  2265 non-null   float64
 29  New Customer Orders        3740 non-null   float64
 30  Returning Customer Orders  1647 non-null   float64
 31  Average Items Per Order    2277 non-null   float64
 32  Discounts (INR)            5216 non-null   float64
 33  Row Count                  5223 non-null   float64
 34  SKU                        2095 non-null   object
 35  Customer Sale Type         5238 non-null   object
 36  Customer ID                5216 non-null   float64
 37  Shipping Country           5230 non-null   object
dtypes: float64(17), object(21)
memory usage: 1.6+ MB

In [43]:
df.describe()

,Order ID,Product ID,Gross Sales (INR),Net Sales (INR),Total Sales (INR),Orders,Returns (INR),Return Rate,Items Sold,Items Returned,Average Order Value (INR),New Customer Orders,Returning Customer Orders,Average Items Per Order,Discounts (INR),Row Count,Customer ID
count,5.230000e+03,3.142000e+03,5.221000e+03,5.223000e+03,5.224000e+03,5219.000000,5203.000000,3211.0,5089.000000,283.000000,2.265000e+03,3740.000000,1647.000000,2277.000000,5216.000000,5223.000000,5.216000e+03
mean,1.043430e+14,9.611715e+13,1.877585e+05,1.591300e+05,1.735468e+05,6.597624,474.298674,0.0,4.115347,5.452297,3.700757e+05,4.963102,2.446873,16.340360,960.149168,10.729083,1.216040e+14
std,2.936214e+14,2.485013e+14,1.338874e+06,1.143849e+06,1.193564e+06,31.019736,11398.963653,0.0,15.000061,25.491627,1.904761e+06,20.436628,10.586079,43.182834,13296.100813,28.848744,3.292951e+14
min,-9.262486e+14,-7.951593e+14,-2.013000e+07,-1.016500e+07,-9.280000e+06,-144.000000,-95000.000000,0.0,-55.000000,-113.000000,-1.624000e+07,-90.000000,-53.000000,-130.000000,-57761.070890,-87.000000,-1.051550e+15
25%,6.849580e+12,7.873492e+12,0.000000e+00,0.000000e+00,1.500000e+02,0.000000,0.000000,0.0,0.000000,0.000000,6.560000e+03,0.000000,0.000000,1.000000,0.000000,1.000000,8.872688e+12
50%,6.951000e+12,8.357400e+12,6.080000e+03,5.520000e+03,6.800000e+03,0.000000,0.000000,0.0,1.000000,0.000000,8.280000e+03,0.000000,0.000000,1.000000,0.000000,1.000000,9.306370e+12
75%,7.010970e+12,8.550100e+12,9.120000e+03,9.000000e+03,1.040000e+04,1.000000,0.000000,0.0,1.000000,1.000000,5.560000e+04,1.000000,1.000000,1.000000,0.000000,1.000000,9.489250e+12
max,9.290166e+14,8.276442e+14,2.281400e+07,2.000900e+07,2.169200e+07,144.000000,432000.000000,0.0,275.000000,113.000000,2.030000e+07,90.000000,53.000000,260.000000,361026.000000,174.000000,1.054460e+15

In [44]:
2. # identified Duplicates
duplicates = df[df.duplicated()]
print("Duplicate rows:", len(duplicates))

Duplicate rows: 33

In [45]:
# Remove Duplicates
df = df.drop_duplicates()

In [46]:
3. # Standardise Date Formats
date_cols = ['Date', 'Transaction Timestamp', 'Order Created At', 'Order Updated At']
for col in date_cols:
    # Replace string 'NAN' with actual Nulls and convert to datetime
    df[col] = pd.to_datetime(df[col].replace('NAN', np.nan), errors='coerce', utc=True)

In [47]:
# idenifying missing values
df.isnull().sum()

Data Source name              442
Date                         3321
Currency                      448
Sales Channel                 446
Transaction Timestamp         750
Order Created At              710
Order Updated At              731
Order ID                      448
Order Name                    441
Country Funnel                447
Geo Location Segment          440
Billing Country               476
Billing Province              731
Billing City                  637
Order Tags                   1911
Product ID                   2516
Product Title                2456
Product Tags                 2425
Product Type                 2456
Variant Title                2457
Gross Sales (INR)             458
Net Sales (INR)               454
Total Sales (INR)             451
Orders                        458
Returns (INR)                 473
Return Rate                  2447
Items Sold                    589
Items Returned               5365
Average Order Value (INR)    3393
New Customer Orders          1931
Returning Customer Orders    4008
Average Items Per Order      3380
Discounts (INR)               464
Row Count                     455
SKU                          3561
Customer Sale Type            441
Customer ID                   463
Shipping Country              447
dtype: int64

In [48]:
# Handling missing value
# - Drop rows missing 'Order ID' (Primary Key) as they cannot be tracked.
df = df.dropna(subset=['Order ID'])

In [49]:
df.dtypes

Data Source name                          object
Date                         datetime64[ns, UTC]
Currency                                  object
Sales Channel                             object
Transaction Timestamp        datetime64[ns, UTC]
Order Created At             datetime64[ns, UTC]
Order Updated At             datetime64[ns, UTC]
Order ID                                 float64
Order Name                                object
Country Funnel                            object
Geo Location Segment                      object
Billing Country                           object
Billing Province                          object
Billing City                              object
Order Tags                                object
Product ID                               float64
Product Title                             object
Product Tags                              object
Product Type                              object
Variant Title                             object
Gross Sales (INR)                        float64
Net Sales (INR)                          float64
Total Sales (INR)                        float64
Orders                                   float64
Returns (INR)                            float64
Return Rate                              float64
Items Sold                               float64
Items Returned                           float64
Average Order Value (INR)                float64
New Customer Orders                      float64
Returning Customer Orders                float64
Average Items Per Order                  float64
Discounts (INR)                          float64
Row Count                                float64
SKU                                       object
Customer Sale Type                        object
Customer ID                              float64
Shipping Country                          object
dtype: object

In [50]:
# - Fill numeric metrics with 0.0 to prevent calculation breaks.
numeric_cols = df.select_dtypes(include=[np.number]).columns
df[numeric_cols] = df[numeric_cols].fillna(0)

In [51]:
# - Fill categorical info with 'unknown' to maintain record count.
string_cols = df.select_dtypes(include=['object']).columns
df[string_cols] = df[string_cols].fillna('unknown')

In [52]:
# Normalize String Column 
for col in string_cols:
    df[col] = df[col].astype(str).str.lower().str.strip()

In [53]:
df.head()

,Data Source name,Date,Currency,Sales Channel,Transaction Timestamp,Order Created At,Order Updated At,Order ID,Order Name,Country Funnel,...,Average Order Value (INR),New Customer Orders,Returning Customer Orders,Average Items Per Order,Discounts (INR),Row Count,SKU,Customer Sale Type,Customer ID,Shipping Country
0,brand a,2026-01-08 00:00:00+00:00,inr,online store,2026-01-08 11:39:42+00:00,2026-01-08 11:39:43+00:00,2026-01-08 11:39:44+00:00,-6.318230e+12,unknown,united arab emirates,...,0.0,0.0,0.0,0.0,0.0,1.0,unknown,first-time,9.052170e+12,unknown
1,brand a,NaT,inr,online store,2026-01-13 06:25:45+00:00,2026-01-13 06:25:47+00:00,2026-01-13 06:25:48+00:00,6.324090e+12,#1053,united states,...,0.0,0.0,0.0,0.0,0.0,1.0,unknown,unknown,9.965681e+14,united states
2,brand a,NaT,inr,online store,2026-01-19 16:16:58+00:00,2026-01-19 16:16:59+00:00,2026-01-19 16:17:00+00:00,6.333300e+12,#1055,united states,...,0.0,0.0,0.0,0.0,0.0,1.0,unknown,first-time,-9.979288e+14,united states
3,brand a,NaT,inr,online store,2026-01-29 15:56:31+00:00,2026-01-29 15:56:32+00:00,NaT,6.345630e+12,#1057,united states,...,0.0,0.0,0.0,0.0,0.0,1.0,unknown,first-time,1.000260e+15,united states
4,brand a,NaT,inr,online store,NaT,2026-01-21 17:02:59+00:00,2026-01-21 17:03:01+00:00,6.335680e+12,#1056,india,...,0.0,0.0,0.0,0.0,0.0,0.0,unknown,first-time,0.000000e+00,india